title: Full Stack Developer === Russell Jones
subtitle: Blog posts and conact information of a Full-Stack Developer and DevOps expert.
description: 'Tech blog posts by moi, Russell Jones.'
email: jonesrussell42@gmail.com
repository: jonesrussell/blog
analytics_code: G-3VJWXMBV5B
js_bundle: app.bundle
url: 'https://blog.jonesrussell42.xyz'
style: dark
listen_for_clients_preferred_style: true
footer: 'follow me on <a href="https://twitter.com/jonesrussell42">twitter</a>'
theme: grape-theme
header_pages:
  - index.markdown
  - about.markdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-json-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .devcontainer/
  - '*.json'
  - webpack.config.js
  - README.md
  - '*.txt'
  - '*.yaml'
  - grape-theme.gemspec
  - Dockerfile
  - default.conf
  - src/
include:
  - _posts
theme_settings:
  title: Russell Jones
  favicon: assets/favicon.ico
  profile:
    image: assets/img/smile.png
    username: Russell Jones
    description: Stuff about web development
    experience:
      - start: '2017-05-03'
        end: '2018-05-06'
        experience: 'company name, title'
    skills:
      - skill: HTML5 & CSS
        value: 100
  icons:
    email: russell@web.net
    linkedin: 'https://www.linkedin.com/in/jonesrussell42/'
    github: jonesrussell
    twitter: jonesrussell42
    youtube: 'null'
paginate: 5
paginate_path: 'blog/page:num'
sass:
  sass_dir: _sass
  style: ':compressed'
bootstrap:
  assets: true
github:
  - metadata
uncss:
  stylesheets:
    - assets/css/main.css
  files:
    - '**/*.html'
  compress: false
  ignore:
    - .is-loading
    - '#titleBar'
  media:
    - print
  timeout: 30
  banner: false
jekyll_admin:
  collections: null
  posts:
    output: true
    sidebar_label: Blog
