# Site settings
title: Web Developer Blog
description: >-
  A resource for web developers, I use modern technologies, best practices, and personal experiences. 
  Explore guides on Laravel, Golang, Docker, and more.
baseurl: "/blog"
url: "https://jonesrussell.github.io"

# Author information
author:
  name: "Russell"
  email: russell@web.net

# Theme settings
remote_theme: JakeSteam/minimaJake@1.0.14
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/jonesrussell"
      title: "GitHub"
    - platform: x
      user_url: "https://x.com/jonesrussell42"
      title: "X"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/jonesrussell42"
      title: "LinkedIn"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/437654/russell"
      title: "Stack Overflow"
    - platform: devto
      user_url: "https://dev.to/jonesrussell"
      title: "DEV.to"
    - platform: youtube
      user_url: "https://www.youtube.com/@fullstackdev42"
      title: "YouTube"
    - platform: link
      user_url: "https://jonesrussell.github.io/me"
      title: "Website"

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: page/:num/

# Content settings
excerpt_separator: ""
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Assets
favicon: "/assets/images/favicon.ico"

# Feed configuration
feed:
  url: "/blog/feed.xml"
