# Site settings
title: Web Developer Blog
description: >- 
  A resource for web developers, I use modern technologies,
  best practices, and personal experiences. Explore guides
  on Laravel, Golang, Docker, and more.
baseurl: "/blog"
url: "https://jonesrussell.github.io"
timezone: America/Toronto
accent_colour: "#2a7ae2"
show_excerpts: true
permalink: /:title/

# Author information
email: jonesrussell42@gmail.com
github_username: jonesrussell
twitter_username: jonesrussell42

# Theme settings
remote_theme: JakeSteam/minimaJake@1.0.14
minima:
  skin: auto
  social_links:
    - { platform: github,        user_url: "https://github.com/jonesrussell" }
    - { platform: linkedin,      user_url: "https://www.linkedin.com/in/jonesrussell42" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/437654/russell" }
    - { platform: x,            user_url: "https://www.x.com/jonesrussell" }
    - { platform: email,        user_url: "mailto:jonesrussell42@gmail.com", user_title: "jonesrussell42@gmail.com" }
    - { platform: code,         user_url: "https://github.com/jonesrussell/blog", user_title: "JakeSteam/blog-programming" }
    - { platform: rss,          user_url: "/feed.xml", user_title: "RSS Feed" }
    - { platform: devto,        user_url: "https://dev.to/jonesrussell" }
    - { platform: youtube,      user_url: "https://www.youtube.com/@fullstackdev42" }

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 10
paginate_path: page/:num/

# Content settings
excerpt_separator: ""
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Custom features
table_of_contents_header: "Jump to:"
post_end_promo: <i><b>Enjoyed this article? You'll like "<a href="https://www.youtube.com/@fullstackdev42">Jake Week Lee</a>", a newsletter of articles & online things!</b></i>

# Assets
favicon: "/assets/images/favicon.ico"
