apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekyll-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jekyll-website
  template:
    metadata:
      labels:
        app: jekyll-website  
    spec:
      containers:
      - name: website
        image: jekyll-app:1.0.0
        ports:
          - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

