version: '3'

tasks:
  default:
    desc: Default task - starts Jekyll server
    deps: [install]
    cmds:
      - task: serve

  clear:
    desc: Clear the terminal screen
    cmds:
      - cmd: clear
        platforms: [linux, darwin]
      - cmd: cls
        platforms: [windows]

  install:
    desc: Install dependencies
    cmds:
      - gem install bundler
      - bundle install

  serve:
    desc: Start Jekyll server
    cmds:
      - bundle exec jekyll serve

  build:
    desc: Build the site
    cmds:
      - bundle exec jekyll build

  clean:
    desc: Clean build files
    cmds:
      - bundle exec jekyll clean

  update:
    desc: Update dependencies
    cmds:
      - bundle update 

  lint:
    desc: Lint markdown files and front matter
    deps: [lint:pull]
    cmds:
      - docker run -v "${PWD}:/workdir" --rm -w /workdir davidanson/markdownlint-cli2 "_posts/**/*.md" "*.md"
      - docker run -v "${PWD}:/workdir" --rm -w /workdir cytopia/yamllint .

  lint:pull:
    desc: Pull required Docker images
    cmds:
      - docker pull pandoc/core:latest
    status:
      - docker image inspect pandoc/core:latest >/dev/null 2>&1

  lint:check:
    desc: Check markdown formatting
    deps: [lint:pull]
    cmds:
      - |
        for file in _posts/*.md; do
          docker run --rm -v ${PWD}:/work -w /work pandoc/core:latest \
            pandoc "$file" -f markdown -t markdown --check
        done

  lint:fix:
    desc: Attempt to fix markdown issues automatically
    cmds:
      - |
        echo "Starting lint:fix task..."
        docker run --rm \
          -v "/home/russell/dev/blog:/workdir" \
          -w /workdir \
          davidanson/markdownlint-cli2 \
          --fix "_posts/**/*.md" "_drafts/**/*.md"