version: '3'

vars:
  HUGO_ENV: '{{.HUGO_ENV | default "development"}}'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  serve:
    desc: Start development server with live reload and drafts
    cmds:
      - hugo server -D --navigateToChanged

  serve:prod:
    desc: Start server in production mode (no drafts)
    cmds:
      - hugo server --navigateToChanged

  build:
    desc: Build site for production
    cmds:
      - hugo --gc --minify
    env:
      HUGO_ENV: production

  build:drafts:
    desc: Build site including drafts
    cmds:
      - hugo --gc --minify -D

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf public/
      - rm -rf resources/_gen/
      - rm -f .hugo_build.lock

  new-post:
    desc: Create a new blog post
    cmds:
      - hugo new posts/{{.CLI_ARGS}}.md
    preconditions:
      - sh: '[ -n "{{.CLI_ARGS}}" ]'
        msg: "Usage: task new-post -- my-post-title"

  stats:
    desc: Show site statistics
    cmds:
      - |
        echo "=== Site Statistics ==="
        echo "Published posts: $(find content/posts -name '*.md' -exec grep -L 'draft: true' {} \; | wc -l)"
        echo "Draft posts: $(find content/posts -name '*.md' -exec grep -l 'draft: true' {} \; | wc -l)"
        echo "Total posts: $(find content/posts -name '*.md' | wc -l)"
        echo "Categories: $(find public/categories -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)"
        echo "Tags: $(find public/tags -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)"

  check:
    desc: Check for common issues
    cmds:
      - hugo --gc --minify --printPathWarnings

  theme:update:
    desc: Update PaperMod theme to latest version
    cmds:
      - cd themes/PaperMod && git pull origin master

  deploy:
    desc: Build and prepare for deployment
    deps:
      - clean
    cmds:
      - hugo --gc --minify
      - echo "Site built successfully in public/"
    env:
      HUGO_ENV: production
