#!/bin/bash

# Help script for Taskfile
# Shows detailed help information

echo "=== Jekyll Blog Taskfile ==="
echo ""
echo "Blog Management:"
echo "  task serve          - Start development server"
echo "  task build          - Build for production"
echo "  task clean          - Clean build artifacts"
echo ""
echo "Content Management:"
echo "  task new-post       - Create new blog post"
echo "  task publish-draft  - Publish a draft"
echo "  task list-drafts    - List draft posts"
echo "  task list-posts     - List published posts"
echo ""
echo "PHP-FIG Guide:"
echo "  task php:install    - Install PHP dependencies"
echo "  task php:test       - Run PHP tests"
echo "  task php:check-style - Check coding standards"
echo "  task php:fix-style  - Fix coding standards"
echo "  task php:analyze    - Run static analysis"
echo ""
echo "Validation:"
echo "  task validate       - Run all validations"
echo "  task validate:content - Validate with Vale"
echo "  task validate:markdown - Validate markdown"
echo "  task validate:yaml  - Validate YAML"
echo "  task validate:php   - Validate PHP code"
echo ""
echo "Setup:"
echo "  task setup          - Complete project setup"
echo "  task setup:ruby     - Setup Ruby environment"
echo "  task setup:php      - Setup PHP environment"
echo "  task setup:tools    - Setup development tools"
echo ""
echo "Development:"
echo "  task dev            - Start development environment"
echo "  task test           - Run all tests"
echo "  task deploy         - Build for deployment"
echo ""
echo "Utilities:"
echo "  task search         - Search content"
echo "  task stats          - Show project statistics"
echo "  task help           - Show this help" 